vsplunk:
  image: busybox
  volumes:
    - /opt/splunk/etc
    - /opt/splunk/var

splunk:
  image: outcoldman/splunk:6.3.2
  hostname: splunk
  volumes_from:
    - vsplunk
  ports:
    - 8000:8000
    - 8088:8088
    - 5005:5005